version: "3.9"

services:
  app-news-stories:
    build: news_stories/.
    container_name: news_stories
    volumes:
      - ./news_stories:/home
    depends_on:
      - redis
    restart: always
    networks:
      - backend-network
    env_file: ./news_stories/.env
    ports:
      - "8000:8000"

  app-news-stories-tests:
    build: news_stories/.
    container_name: news_stories_tests
    volumes:
      - ./news_stories:/home
    depends_on:
      - redis
    networks:
      - backend-network
    env_file: ./news_stories/.env
    command: ["pytest", "tests/"]
    environment:
      - ENV=test

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend-network
    volumes:
      - redis-data:/data

networks:
  backend-network:

volumes:
  redis-data:
