export const newsData = [
  {
    id: 1,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 2,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 3,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 4,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 5,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 6,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 7,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 8,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 9,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
  {
    id: 10,
    title: 'Breaking News: React is Awesome',
    url: 'https://reactjs.org/',
    author: 'Dan Abramov',
    score: 150,
    time: 1633036800,
  },
];
